#319 年齢を表示できるようにする
thinkingreed-inc/F-RevoCRM pull request #468
Opened 2022-01-25 08:27 UTC by kkouta

##  関連Issue / Related Issue

- fix #319 

##  不具合の内容 / Bug

1. 生年月日から年齢を表示できるようにする。

##  原因 / Cause

1. 

##  変更内容 / Details of Change

1. ワークフローに「age」を追加し年齢を更新できるようにした

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/95267222/150939170-5671a249-d243-4221-aad5-bcdaf6595d7c.png)

## 影響範囲  / Affected Area

ワークフローのage関数の範囲
## チェックリスト / Check List

- [x] 自らテストを行った
- [x] 不必要な変更が無い
- [x] 影響範囲の検討を行った

## 備考 / Remarks

2022-01-25 11:25 UTC, Remicck requested changes
```
'age' => "get_age((contact_id : (Contacts) birthday))",
```
この部分、ワークフローで更新したときにcontact_idとして登録されている日付項目を持っているモジュールでしか正常に動きません。

どんな日付項目が出たとしても、日付項目→年齢に変換できるようにしてください。
なお、この処理はその性質上、毎日12時に実行することを想定している処理だと思います（日々年齢は変更されるので）

同時に、スケジュールワークフローでの動作の確認をお願いします。

2022-01-25 11:26 UTC, Remicck commented
例えば、以下のようなコードになったとしても、入ってきた値に応じて動くようにしたいです。
```
'age' => "get_age(date)
```

2022-02-01 09:03 UTC, kkouta commented
　ワークフローの関数にてageを選んだ際にデフォルトでget_age((contact_id : (Contacts) birthday))と表示されるようになっていますが、(contact_id : (Contacts) birthday)の部分をほかの日付項目に変えたとしても現在の日付と比較してその差の年が返されるようになっています。
　すぐにスケジュールワークフローでの動作の確認も致します。

2022-05-18 09:04 UTC, kkouta commented
get_ageにどのような日付項目が渡されても年齢に変換できるようになっています。
年齢項目は顧客担当者に対して使うと思い、デフォルト値として顧客担当者の誕生日を引数にしていました。
スケジュールワークフローでの動作の確認も行います。

![image](https://user-images.githubusercontent.com/95267222/169000189-e3b72a7f-acdc-42ef-98d6-cdbcb7e9c8f9.png)

2022-11-12 03:59 UTC, Remicck approved these changes

2022-11-12 03:59 UTC, merged